### PR TITLE
Enhancement: Add tests for database package with ika

### PR DESCRIPTION
**Pull request by mod**

### CODE REVIEW

**Comment by mod** [comment]
Broken pull request this doesn't work in ika

**Comment by dpatsora** [comment]
@mod @xenirio I cherry-picked commit from this PR https://github.com/openware/pkg/pull/10 here.

**Comment by mod** [comment]
test with export GO111MODULE=off

**Comment by xenirio** [comment]
> @mod @xenirio I cherry-picked commit from this PR https://github.com/openware/pkg/pull/10 here.

Ok. Closing my PR now.

**Pull request merged**
